name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 767397755066.dkr.ecr.us-west-1.amazonaws.com

    - name: Build, tag, and push Docker image
      run: |
        docker build -t my-image:latest .
        docker tag my-image:latest 767397755066.dkr.ecr.us-west-2.amazonaws.com/my-repository:latest
        docker push 767397755066.dkr.ecr.us-west-2.amazonaws.com/my-repository:latest
         aws cloudformation deploy --template-file cloudformation.yml --stack-name node-app-stack --capabilities CAPABILITY_NAMED_IAM
